// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd6irbfGxhBJqbzHby5eTdSHcyFxKV5g',
    appId: '1:808476418164:android:b125ea89490ca374a37121',
    messagingSenderId: '808476418164',
    projectId: 'medicapp-f2c65',
    databaseURL: 'https://medicapp-f2c65-default-rtdb.firebaseio.com',
    storageBucket: 'medicapp-f2c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbd8e4Fy92QAvfEeKn5zySdHMBgzsdsUE',
    appId: '1:808476418164:ios:785d599628435e94a37121',
    messagingSenderId: '808476418164',
    projectId: 'medicapp-f2c65',
    databaseURL: 'https://medicapp-f2c65-default-rtdb.firebaseio.com',
    storageBucket: 'medicapp-f2c65.firebasestorage.app',
    iosClientId: '808476418164-0ea908a6k30jv1l931etihh1oq1870bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );
}
